wandb_version: 1

norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696407440.281736
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.11
      8:
      - 1
      - 5
      13: linux-x86_64
